name: base_project
description: A new Flutter project.

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  freezed_annotation: ^0.7.1
  indonesia: ^1.0.1
  date_format: ^1.0.8
  cupertino_icons: ^0.1.3
  flutter_alert: ^0.4.0
  flutter_cupertino_date_picker: ^1.0.26
  easy_localization: ^2.3.2
  flutter_secure_storage: ^3.3.3
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_native_splash: ^0.1.9
  freezed: ^0.10.9
  build_runner: ^1.10.0
  # run `flutter pub run build_runner watch --delete-conflicting-outputs`

flutter_launcher_name:
  name: "Base Project Flutter"
# run `flutter pub run flutter_launcher_name:main`

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/app_icon_adaptive.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/app_icon_adaptive.png" # only available for Android 8.0 devices and above
# run `flutter pub run flutter_launcher_icons:main`

flutter_native_splash:
  image: assets/images/icon.png
  color: "ffffff"
# run `flutter pub pub run flutter_native_splash:create`

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 700
    - family: AvenirNextLTPro-Regular
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
    - family: AvenirNextLTPro-Demi
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Demi.otf
    - family: AvenirNextLTPro-Bold
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf