name: base_project
description: A new Flutter project.

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  freezed_annotation: ^0.7.1
  indonesia: ^1.0.1
  date_format: ^1.0.8
  cupertino_icons: ^0.1.3
  flutter_alert: ^0.4.0
  flutter_cupertino_date_picker: ^1.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_native_splash: ^0.1.9
  freezed: ^0.10.9
  build_runner: ^1.10.0
  # run `flutter pub run build_runner watch --delete-conflicting-outputs`

flutter_launcher_name:
  name: "Delivery Order"
# run `flutter pub run flutter_launcher_name:main`

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
# run `flutter pub run flutter_launcher_icons:main`

flutter_native_splash:
  image: assets/icon.png
  color: "ffffff"
# run `flutter pub pub run flutter_native_splash:create`

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
  #   - images/a_dot_ham.jpeg